version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - goreleaser release --clean --skip=validate

  release:
    desc: Release
    cmds:
      - goreleaser release --clean

  generate-ui:
    cmds:
      - cd ui && mise exec -- task build
      - rm -rf resources/gen/ui && mkdir -p resources/gen/ui && cp -r ui/dist/* resources/gen/ui/

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct

  mingo:
    cmds:
      - mise exec go@1.25.2 -- mise install 'go:github.com/bobg/mingo/cmd/mingo@0.14.0'
      - mise exec 'go:github.com/bobg/mingo/cmd/mingo@0.14.0' -- mingo -tests -v
