version: 3

tasks:
  install:
    cmds:
      - pnpm install

  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm run build

  dev:
    desc: Dev
    deps: [ install ]
    cmds:
      - pnpm run dev
